# Generated by Django 2.0 on 2017-12-31 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='user',
            new_name='author',
        ),
        migrations.AddField(
            model_name='post',
            name='headline',
            field=models.CharField(default='poule', max_length=400),
            preserve_default=False,
        ),
    ]
